<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Sparky.Tests</AssemblyName>
    <RootNamespace>Sparky.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="CsCheck" Version="4.4.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../src/core/core.csproj" />
    <ProjectReference Include="../src/2d/2d.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(VINTAGE_STORY)' != ''">
    <ProjectReference Include="../src/mod/mod.csproj" />
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(VINTAGE_STORY)' == ''">
    <Compile Remove="mod/**" />
  </ItemGroup>
</Project>
