<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sparky.Voxel</AssemblyName>
    <RootNamespace>Sparky.Voxel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../mna/Sparky.Mna.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sparky.Tests" />
  </ItemGroup>
</Project>
